{% set name = "zuko" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zuko-{{ version }}.tar.gz
  sha256: cd282dbbb4c845d2a104070b7780f128420b27296fda5b1731f0c84dbc99388e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.20.0
    - pytorch >=1.12.0

test:
  imports:
    - zuko
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Normalizing flows in PyTorch
  dev_url: https://github.com/probabilists/zuko
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankier
